export const ADD_ROW = "ADD_ROW";
export const REMOVE_ROW = "REMOVE_ROW";
export const UPDATE_ROW = "UPDATE_ROW";

export const TOGGLE_ROW_SELECTION = "TOGGLE_ROW_SELECTION";
export const TOGGLE_ALL_ROWS_SELECTION = "TOGGLE_ALL_ROWS_SELECTION";

export const OPEN_FORMULA_DIALOG = "OPEN_FORMULA_DIALOG";
export const CLOSE_FORMULA_DIALOG = "CLOSE_FORMULA_DIALOG";

export const UPDATE_FORMULA = "UPDATE_FORMULA";
export const ADD_FORMULA = "ADD_FORMULA";
